import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import http from 'node:http';import {once} from 'node:events';import {spawnSync,spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {convertNumber} from './convert.mjs';import {createConversionServer} from './http.mjs';
const directory=await fs.mkdtemp(path.join(os.tmpdir(),'cnnum-host-')),checks=[];let server;
const cli=fileURLToPath(new URL('./number-cli.mjs',import.meta.url));
function run(args,input='',status=0){const p=spawnSync(process.execPath,[cli,...args],{input,encoding:'utf8',windowsHide:true,timeout:15000,maxBuffer:8000000});assert.equal(p.status,status,p.stderr+p.stdout);return p;}
try{
  assert.equal(convertNumber({operation:'cn2an',mode:'smart',input:'9007199254740993'}),'9007199254740993');assert.throws(()=>convertNumber({operation:'cn2an',input:123}),/string/);assert.throws(()=>convertNumber({operation:'transform',input:'x',direct:'yes'}),/boolean/);checks.push('Exact string API, unsafe number and invalid option rejection');
  const source='😀共1百23元，三分之二';const spans=convertNumber({operation:'spans',input:source});for(const span of spans)assert.equal(source.slice(span.start,span.end),span.source);assert.equal(spans[0].start,3);checks.push('Actual JS Unicode span offsets');
  assert.equal(run(['cn2an','--mode','smart','--input','-1.2万']).stdout,'-12000\n');assert.equal(run(['currency','--rounding','half-up','--prefix','人民币','--input','9.995']).stdout,'人民币壹拾元整\n');assert.equal(run(['transform','--direction','an2cn'],'2026年9月17日').stdout,'二零二六年九月十七日\n');run(['cn2an','--input','一百二'],'',2);run(['cn2an','--input'],'',1);checks.push('CLI modes, options, stdin and nonzero errors');
  const input=path.join(directory,'input.txt');await fs.writeFile(input,'-0.0012300');assert.equal(run(['an2cn','--file',input]).stdout,'负零点零零一二三零零\n');await fs.writeFile(input,Buffer.from([255]));run(['an2cn','--file',input],'',1);checks.push('File input and strict UTF-8');
  const batch=[{operation:'cn2an',mode:'normal',input:'一百二'},{operation:'cn2an',input:'百'},{operation:'an2cn',input:'1000000000000'}].map(JSON.stringify).join('\n')+'\n';const results=run(['jsonl'],batch,2).stdout.trim().split('\n').map(JSON.parse);assert.deepEqual(results.map(x=>x.ok),[true,false,true]);assert.equal(results[2].result,'一万亿');checks.push('JSONL continues after a rejected record and returns failure status');
  const batchFile=path.join(directory,'batch.jsonl'),line=JSON.stringify({operation:'cn2an',mode:'smart',input:'1百23'})+'\n';await fs.writeFile(batchFile,line.repeat(12000));const child=spawn(process.execPath,[cli,'jsonl','--file',batchFile],{windowsHide:true,stdio:['ignore','pipe','pipe']});let count=0,errors='';child.stderr.setEncoding('utf8');child.stderr.on('data',x=>errors+=x);const exited=once(child,'exit');for await(const chunk of child.stdout){count+=chunk.toString().split('\n').length-1;await new Promise(resolve=>setTimeout(resolve,1));}assert.equal((await exited)[0],0,errors);assert.equal(count,12000);checks.push('12000 streamed JSONL records with a slow output reader');
  const long='一'.repeat(262144);assert.equal(convertNumber({operation:'transform',input:long}),long);assert.throws(()=>convertNumber({operation:'transform',input:long+'一'}),/length/);checks.push('Maximum sentence and bounded invalid numeral run');
  server=createConversionServer();server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`;
  async function post(body,headers={'content-type':'application/json'}){const r=await fetch(base+'/convert',{method:'POST',headers,body});return {status:r.status,body:await r.json()};}
  assert.equal((await fetch(base+'/health')).status,200);let result=await post(JSON.stringify({operation:'cn2an',input:'壹万贰',mode:'normal'}));assert.equal(result.status,200);assert.equal(result.body.result,'12000');result=await post(JSON.stringify({operation:'cn2an',input:'百'}));assert.equal(result.status,422);checks.push('Real loopback HTTP health, conversion and rejected input');
  assert.equal((await post('{')).status,400);assert.equal((await post(Buffer.from([255]))).status,400);assert.equal((await post('{}',{'content-type':'text/plain'})).status,415);assert.equal((await fetch(base+'/convert')).status,405);assert.equal((await fetch(base+'/missing')).status,404);assert.equal((await post('x'.repeat(2097153))).status,413);checks.push('HTTP JSON, UTF-8, type, method, path and declared-size errors');
  const chunked=await new Promise((resolve,reject)=>{const req=http.request(base+'/convert',{method:'POST',headers:{'content-type':'application/json'}},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.write('x'.repeat(1048576));req.end('y'.repeat(1048577));});assert.equal(chunked,413);checks.push('HTTP chunked body limit');
  const concurrent=await Promise.all(Array.from({length:20},(_,i)=>post(JSON.stringify({operation:'an2cn',input:String(i)}))));assert(concurrent.every(x=>x.status===200));checks.push('Concurrent independent HTTP requests');
  const report={utc:new Date().toISOString(),passed:checks.length,checks,streamingJsonlRecords:12000,http:'Actual loopback Node HTTP; service closed after checks'};await fs.writeFile(new URL('../evidence/host-validation.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(`${checks.length} CLI/API/HTTP groups passed`);
}finally{if(server){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}if(path.dirname(path.resolve(directory))!==path.resolve(os.tmpdir())||!path.basename(directory).startsWith('cnnum-host-'))throw Error('Unsafe cleanup path');await fs.rm(directory,{recursive:true,force:true});}
